#include "findingKeyLength.h"
#include "chiSquaredStatistic.h"


int main()
{
    FILE* inputFilePtr;
    FILE* outFilePtr;
    FILE* letterFrequencyFilePtr;
    char* vigenereCipher;
    PeriodAverageIC* possiblePeriods;
    PeriodAverageIC* bestPossiblePeriods;
    int contor1, contor2, contor3;
    char** substrings;
    TextWithChiSquared* chiSquaredStatistics;
    TextWithChiSquared* minChiSquaredStatistic;
    int minChiSquaredNumber;
    EnglishLetterFrequency* englishLetterFrequencies;

    if((inputFilePtr = fopen("input.txt", "r")) == NULL) {
        printf("Error!");
        exit(1);
    }

    if((outFilePtr = fopen("output.txt", "w")) == NULL) {
        printf("Error!");
        exit(1);
    }

    if((letterFrequencyFilePtr = fopen("lettersProbabilities.txt", "r")) == NULL) {
        printf("Error when opening lettersProbabilities file!");
        exit(1);
    }
    englishLetterFrequencies = getEnglishLetterFrequencies(letterFrequencyFilePtr);
    vigenereCipher = getTextFromFile(inputFilePtr);

    possiblePeriods = computeICForPeriods(outFilePtr, vigenereCipher, MAX_PERIOD);
    bestPossiblePeriods = findPossiblePeriods(possiblePeriods, FIRST_BEST_PERIODS, MAX_PERIOD);
    fprintf(outFilePtr, "\n\n***** Possible periods info:\n");
    fprintf(outFilePtr, "period\t|\taverage IC");
    for(contor1 = 0; contor1 < FIRST_BEST_PERIODS; contor1++) {
        fprintf(outFilePtr, "\n %d\t\t|\t%f", possiblePeriods[contor1].period, possiblePeriods[contor1].IC);
    }
    fflush(outFilePtr);

    fprintf(outFilePtr, "\n\n***** Chi Squared Statistics: ");

    for(contor1 = 0; contor1 < FIRST_BEST_PERIODS; contor1++)
    {
        substrings = getSubstringsForPeriod(vigenereCipher, bestPossiblePeriods[contor1].period);

        fprintf(outFilePtr, "\n\n\t period: %d", bestPossiblePeriods[contor1].period);
        for(contor2 = 0; contor2 < bestPossiblePeriods[contor1].period; contor2++)
        {
            fprintf(outFilePtr, "\n\n\tsubstring no.%d :  %s",contor2, substrings[contor2]);
            fprintf(outFilePtr, "\nPlain text\tchi squared value\tkey");

            chiSquaredStatistics = computeChiSquaredForCipher(substrings[contor2], englishLetterFrequencies);

            ///write to file the chi-squared values for each string generated by Caesar brute force attack
            writeChiSquaredStatisticToFile(outFilePtr, chiSquaredStatistics, 26);

            minChiSquaredStatistic = getFirstTextWithChiSq(chiSquaredStatistics, FIRST_BEST_KEYS, 26);
            fprintf(outFilePtr, "\n\n***** Possible key values for the element no. %d: ", contor2);
            writeChiSquaredStatisticToFile(outFilePtr, minChiSquaredStatistic, FIRST_BEST_KEYS);

        }
    }

    printf("\n\n***** Check the output.txt file view the results *****\n\n");

    free(minChiSquaredStatistic);
    free(chiSquaredStatistics);
    free(bestPossiblePeriods);
    free(possiblePeriods);
    free(vigenereCipher);
    fclose(inputFilePtr);
    fclose(letterFrequencyFilePtr);
    fclose(outFilePtr);
    return 0;
}
